apiVersion: v1  

kind: Secret  
metadata:  
  name: influxdb-secrets  
type: Opaque  
stringData:  
  
  DOCKER_INFLUXDB_INIT_MODE: setup 
  DOCKER_INFLUXDB_INIT_USERNAME: influxuser  
  DOCKER_INFLUXDB_INIT_PASSWORD: influxpasswd  
  DOCKER_INFLUXDB_INIT_ORG: k6io
  DOCKER_INFLUXDB_INIT_BUCKET: k6-load-test
  DOCKER_INFLUXDB_INIT_RETENTION: 1w
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 19da47ca-49a2-4aa6-8856-c31724894fbd
  